name: Build Windows Executable

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller playwright reportlab pillow requests PyQt5

      - name: Install Playwright Browsers
        env:
          PLAYWRIGHT_BROWSERS_PATH: 0
        run: playwright install chromium

      - name: Build Executable with PyInstaller
        run: |
          pyinstaller --onefile --windowed --add-data "lux_official_logo.png;." Scrapers.py

      - name: Upload Executable
        uses: actions/upload-artifact@v3
        with:
          name: CarScraper-Windows
          path: dist/
